# Generated by Django 5.1.6 on 2025-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('organizador', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#0D6EFD', max_length=20)),
            ],
        ),
    ]
