# Generated by Django 5.1.6 on 2025-07-30 16:09

import agenda.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_historialevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=agenda.models.ruta_respaldo_evento, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_respaldo', to='agenda.evento')),
            ],
        ),
    ]
