# Generated by Django 5.1.6 on 2025-07-31 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_archivorespaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeticiones', to='agenda.evento'),
        ),
    ]
