# Generated by Django 5.1.6 on 2025-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_evento_evento_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_limite_repeticion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de repetición'),
        ),
        migrations.AddField(
            model_name='evento',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='repetir',
            field=models.BooleanField(default=False, verbose_name='¿Es recurrente?'),
        ),
    ]
