# Generated by Django 5.1.6 on 2025-08-13 16:15

import django.db.models.deletion
import firmaElectronica.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=firmaElectronica.models.path_firmas)),
                ('nombre_original', models.CharField(max_length=255)),
                ('api_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('proceso', 'En proceso'), ('firmado', 'Firmado'), ('error', 'Error')], db_index=True, default='proceso', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='firmaElectr_estado_49f1a1_idx')],
            },
        ),
    ]
