# Generated by Django 5.1.6 on 2025-05-06 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('departamento', models.CharField(choices=[('direccion', 'Dirección'), ('administrativo', 'Administrativo'), ('financiero', 'Financiero'), ('recursos_humanos', 'Recursos Humanos'), ('tecnologia', 'Tecnología'), ('comercial', 'Comercial'), ('operaciones', 'Operaciones'), ('legal', 'Legal'), ('marketing', 'Marketing'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('permiso_agenda', models.BooleanField(default=False, verbose_name='Acceso al módulo de Agenda')),
                ('permiso_firma', models.BooleanField(default=False, verbose_name='Acceso al módulo de Firma Electrónica')),
                ('es_admin_agenda', models.BooleanField(default=False, verbose_name='Administrador de Agenda')),
                ('es_admin_firma', models.BooleanField(default=False, verbose_name='Administrador de Firma Electrónica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
