# Generated by Django 5.1.6 on 2025-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_es_admin_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=10),
        ),
    ]
